<a href="https://colab.research.google.com/github/pavanrajanala/Ipl2026Analysis/blob/main/Ipl2026Analysis_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded = files.upload()

Saving batting_stats.csv to batting_stats.csv
Saving bowling_stats.csv to bowling_stats.csv
Saving deliveries.csv to deliveries.csv
Saving ipl2026_preview.png to ipl2026_preview.png
Saving matches.csv to matches.csv
Saving points_table.csv to points_table.csv

In [3]:
matches = pd.read_csv('matches.csv')
batting_stats = pd.read_csv('batting_stats.csv')
bowling_stats = pd.read_csv('bowling_stats.csv')
delivery = pd.read_csv('deliveries.csv')
points_table=pd.read_csv('points_table.csv')

/tmp/ipykernel_7338/3018486482.py:4: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  delivery = pd.read_csv('deliveries.csv')

In [4]:
matches.head()
batting_stats.head()
bowling_stats.head()
delivery.head()
points_table.head()

   pos                         team  played  won  lost  no_result  points
0    1  Royal Challengers Bengaluru      16   11     5          0      22
1    2               Gujarat Titans      17   10     7          0      20
2    3             Rajasthan Royals      16    9     7          0      18
3    4          Sunrisers Hyderabad      15    9     6          0      18
4    5                 Punjab Kings      14    7     6          1      15

In [10]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=points_table)

https://docs.google.com/spreadsheets/d/1kElxGaXiAc6gqKo04GOsFWxGWH9ENTq5eF9CH_rtjcE/edit#gid=0

In [5]:
matches.head()

,season,date,match_id,venue,city,toss_winner,toss_decision,player_of_match,winner,team1,team2,win_by_runs,win_by_wickets
0,2026,2026/03/28,1527674,"M Chinnaswamy Stadium, Bengaluru",Bengaluru,Royal Challengers Bengaluru,field,JA Duffy,Royal Challengers Bengaluru,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,0
1,2026,2026/03/29,1527675,"Wankhede Stadium, Mumbai",Mumbai,Mumbai Indians,field,SN Thakur,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,0,0
2,2026,2026/03/30,1527676,"Barsapara Cricket Stadium, Guwahati",Guwahati,Rajasthan Royals,field,N Burger,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,0,0
3,2026,2026/03/31,1527677,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,Punjab Kings,field,C Connolly,Punjab Kings,Gujarat Titans,Punjab Kings,0,0
4,2026,2026/04/01,1527678,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Delhi Capitals,field,Sameer Rizvi,Delhi Capitals,Lucknow Super Giants,Delhi Capitals,0,0

In [6]:
batting_stats.head()

,batter,batting_team,innings,runs,balls_faced,fours,sixes,dismissals,highest,avg,sr,50s,100s
0,V Suryavanshi,Rajasthan Royals,16,1552.0,688,126,144,32,206.0,48.50,225.58,6,6
1,Shubman Gill,Gujarat Titans,16,1464.0,944,148,66,32,208.0,45.75,155.08,4,7
2,B Sai Sudharsan,Gujarat Titans,17,1444.0,962,150,60,32,200.0,45.12,150.10,0,9
3,V Kohli,Royal Challengers Bengaluru,16,1350.0,850,146,50,24,210.0,56.25,158.82,5,6
4,H Klaasen,Sunrisers Hyderabad,15,1248.0,826,96,62,26,138.0,48.00,151.09,6,6

In [7]:
bowling_stats.head()

,bowler,matches,balls,runs_given,wickets,overs,economy,avg,sr
0,K Rabada,17,800,1262.0,58,133.2,9.46,21.76,13.79
1,B Kumar,16,782,1008.0,56,130.2,7.73,18.00,13.96
2,JC Archer,16,758,1132.0,50,126.2,8.96,22.64,15.16
3,A Kamboj,14,630,1070.0,42,105.0,10.19,25.48,15.00
4,Rashid Khan,17,696,1054.0,42,116.0,9.09,25.10,16.57

In [9]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=bowling_stats)

https://docs.google.com/spreadsheets/d/18TTvaWRDuVxNX85jOGcnobChCMdp9RaUehjWUHN5hv4/edit#gid=0

In [8]:
delivery.head()

,match_id,season,date,venue,inning,over_ball,over_ball2,batting_team,bowling_team,batter,...,player_dismissed,c8,c9,c10,c11,c12,over,ball_num,runs_total,is_wicket
0,1527674,2026,2026-03-28,"M Chinnaswamy Stadium, Bengaluru",1.0,0.1,0.1,Sunrisers Hyderabad,Royal Challengers Bengaluru,TM Head,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0.0,False
1,1527674,2026,2026-03-28,"M Chinnaswamy Stadium, Bengaluru",1.0,0.2,0.2,Sunrisers Hyderabad,Royal Challengers Bengaluru,TM Head,...,NaN,NaN,NaN,NaN,NaN,NaN,0,2,1.0,False
2,1527674,2026,2026-03-28,"M Chinnaswamy Stadium, Bengaluru",1.0,0.3,0.3,Sunrisers Hyderabad,Royal Challengers Bengaluru,Abhishek Sharma,...,NaN,NaN,NaN,NaN,NaN,NaN,0,3,0.0,False
3,1527674,2026,2026-03-28,"M Chinnaswamy Stadium, Bengaluru",1.0,0.4,0.4,Sunrisers Hyderabad,Royal Challengers Bengaluru,Abhishek Sharma,...,NaN,NaN,NaN,NaN,NaN,NaN,0,4,6.0,False
4,1527674,2026,2026-03-28,"M Chinnaswamy Stadium, Bengaluru",1.0,0.5,0.5,Sunrisers Hyderabad,Royal Challengers Bengaluru,Abhishek Sharma,...,NaN,NaN,NaN,NaN,NaN,NaN,0,5,0.0,False